# Site settings
BaseURL = "https://rudderandoar.com"
languageCode = "en-us"
title = "Rudder and Oar"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"


  # Navigation
  [params.navigation]
    brand = "Rudder and Oar"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    services = "Services"
    portfolio = "Portfolio"
    about = "About"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    # [[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Rudder + Oar"
    subtitle = "Hand Lettered Goods to Delight + Inspire"
    # buttonText = "Tell me more"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-shopping-bag"
      title = "Shop"
      description = "We have a wide variety of projects available for sale on Etsy. Browse Rudder and Oar products in our online shop!"
      url = "https://www.etsy.com/shop/rudderandoar"

    [[params.services.row.list]]
      icon = "fa-calendar"
      title = "Events"
      description = "Use words to make your event beautiful and memorable. Wedding signs or vows, invitation or announcement calligraphy, seating charts and menus are a few examples that I look forward to lettering for your special occasion."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-paint-brush"
      title = "Custom Projects"
      description = "From creative projects like penning quotes to capturing memories from a vacation, get in touch with your idea and let’s get creating."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "From print to packaging, everything is created with intention and love."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = ""
    endpoint = "Let's Collaborate"


    [[params.about.events]]
      img = "paper_goods.jpg"
      # date = "2009-2011"
      title = "Creation"
      description = "Rudder and Oar has grown out of a love of letter writing, paper goods and the power of words. Words have the ability to 'rudder' us in one direction or another and can give us the forward momentum needed to move, like an ‘oar’ in the water."
    [[params.about.events]]
      img = "sunrise_beach.jpg"
      # date = "2009-2011"
      title = "Inspiration"
      description = "Poignant quotes, great literature, conversations with friends or song lyrics fuel the desire to create word based art. Crashing waves, sandy beaches, dipping a paddle into calm lake, tall evergreens, moss covered paths, falling snow and the stillness of a dense forest also serve as inspiration and can be seen weaved into projects."
    [[params.about.events]]
      img = "change_world.jpg"
      # date = "2009-2011"
      title = "Your Project"
      description = "Let's make all your word dreams come true. Contact me with your special event, words or crazy design ideas and let's get creating. "

  # Team section
  [params.team]
    enable = true
    center = true
    title = "Hello!"
    subtitle = """I'm Jen Thomas. A West Michigan native living in Boston after a few other stops along the way. I'm the owner and calligrapher here at Rudder and Oar and love all things water, woods and paper goods."""
    description = ""

    [[params.team.members]]
      img = "jenforweb.jpg"
      name = "Jen Thomas"
      bio = """### Favorite things:
* Waking up in a tent
* Water (especially Lake Michigan) and trees
* Paddling (from the BACK of the canoe)
* New Adventures (see below)
* ALL the chips and salsa
* Morning coffee
* Library dates
### Current Adventures:

* Boat Restoration Project
* Hike the 48 peaks over 4,000 ft in the NH White Mountains
"""
      #social = [["fa-twitter", "#"]]


  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "We'd love to hear from you."
    buttonText = "Send message"

    email = "rudderandoar@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Your message has been sent! We'll get back to you as soon as we possibly can."
    error = "Oops! For some reason your message didn't send. Please contact us at rudderandoar@gmail.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Made with love in Boston"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/rudderandoar/"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-etsy"
      link = "https://www.etsy.com/shop/rudderandoar"
      title = "Etsy"

    # [[params.footer.quicklinks]]
    #  text = "Privacy Policy"
    #  link = "#"

    # [[params.footer.quicklinks]]
    #  text = "Terms of Use"
    #  link = "#"
